# Code Generated by Sidekick is for learning and experimentation purposes only.
from sqlalchemy import create_engine, text
from html import escape

# Assume `engine` is a valid SQLAlchemy engine object
engine = create_engine('sqlite:///example.db')

def get_user(username):
    with engine.connect() as connection:
        # Use parameterized query to avoid SQL injection
        query = text("SELECT * FROM users WHERE username = :username")
        result = connection.execute(query, username=username).fetchall()
        
        # Output encoding to prevent XSS when displaying the data
        encoded_result = [escape(str(row)) for row in result]
        
        return encoded_result

user = get_user("admin")
print(user)
