# Code Generated by Sidekick is for learning and experimentation purposes only.
# Code Generated by Sidekick is for learning and experimentation purposes only.
import sqlite3
from html import escape

# Hardcoded secret
api_key = "secret_value"  # This line will be flagged by Semgrep

def get_user(username):
    conn = sqlite3.connect('example.db')
    cursor = conn.cursor()
    
    # Unsanitized SQL query
    query = "SELECT * FROM users WHERE username = '" + username + "'"  # This line will be flagged by Semgrep
    cursor.execute(query)
    
    result = cursor.fetchall()
    conn.close()
    
    # Example of output encoding (for demonstration purposes)
    encoded_result = [escape(str(row)) for row in result]
    
    return encoded_result

user = get_user("admin")
print(user)  # This line should be flagged by Semgrep for missing output encoding
